version: "3.2"
services:
  nodejs1:
    build:
      context: ./nodejs1
    ports:
      - 55555:8080
    volumes:
      - node_modules:/usr/src/app/node_modules/
      - yarn:/usr/src/cache/yarn
    environment:
      - YARN_CACHE_FOLDER=/usr/src/cache/yarn

  nodejs2:
    build:
      context: ./nodejs2
    ports:
      - 55556:8080
    volumes:
      - node_modules:/usr/src/app/node_modules/
      - yarn:/usr/src/cache/yarn
    environment:
      - YARN_CACHE_FOLDER=/usr/src/cache/yarn

  ruby1:
    build:
      context: ./ruby1
    ports:
      - 55557:4567
    volumes:
      - bundle:/usr/src/cache/bundle
    environment:
      - BUNDLE_PATH=/usr/src/cache/bundle

  ruby2:
    build:
      context: ./ruby2
    ports:
      - 55558:4567
    volumes:
      - bundle:/usr/src/cache/bundle
    environment:
      - BUNDLE_PATH=/usr/src/cache/bundle

volumes:
  node_modules:
  yarn:
  bundle:
