source 'https://rubygems.org'

gem "sinatra", "~> 2.0"
gem "json", "~> 2.3"
gem "nokogiri"
gem "rack", "~>2.0"
gem "rspec", :require => "spec"
gem "sassc", "~> 2.4"
gem "tzinfo", "~> 2.0"
gem "rubyzip", "~> 2.3"
